### ISSUE TITLE
for loop sass enhancement

### ISSUE THREAD

**Issue by chef-danny-d** [chef-danny-d/isaac#10]
currently the background images are being loaded into each div with the different ids one by one in different statements.

the hope here is to make a ```@for``` loop that will use an index from 1 to 8 to add photos 1 through 8 into divs with ids 1 through 8. i tried my version and it kept throwing an error for not being passed in the ```$photos``` variable. 

https://github.com/chef-danny-d/isaac/blob/ad09403c73c7da1c527b87b7e4c3b5111824efb3/_scss/style.scss#L371-L418

**Comment by Alexius08** [comment]
May I see how you tried to do it using the for loop?

**Comment by chef-danny-d** [comment]
```scss
@for $i from 1 through 8{
  #pic#{$i}{
    background-repeat: no-repeat; 
    background-position: center center; 
    background-size: cover; 
    background-image: $photos-#{$i}; 
  }
}
```
This was the code that I tried and i'm stuck in passing the variable ```$photos-``` into the loop to execute.
