### ISSUE TITLE
linear gradient CSS3 fix

### ISSUE THREAD

**Issue by chef-danny-d** [chef-danny-d/isaac#8]
```css
.overlay, .photos__grid__img--overlay {
    background: -webkit-gradient(linear, left top, left bottom, from(#e2e2e2), color-stop(#beb5a5) ,to(#645b4e));
    background: -webkit-linear-gradient(#e2e2e2, #beb5a5 ,#645b4e);
    background: -o-linear-gradient(#e2e2e2, #beb5a5 ,#645b4e);
    background: linear-gradient(#e2e2e2, #beb5a5 ,#645b4e);
}
```

no percentage values. need to scan through ```style.scss``` for mixins and change parameters

https://github.com/chef-danny-d/isaac/blob/31dd19334670b7f91e33d40e658220d219bcda18/_scss/_variables.scss#L21
